[tool.bumpver]
current_version = "2.7.0"
version_pattern = "MAJOR.MINOR.PATCH"
commit_message = "bump version {old_version} -> {new_version}"
commit = true
tag = true
push = false

[tool.bumpver.file_patterns]
"MediaDurationRecursiveChecker.py" = [
    '__version__ = "{version}"',
]
